- herms.hs
I noticed that the recipe book was read in multiple places so figured out it was a good thing to carve this out as a toplevel function.
Also got rid of a bunch of partial matches leading to runtime exceptions when passing invalid arguments to the executable.
> A handful of modifications

- Contributing.md
- Utils.hs
- herms.hs
I've introduced Utils.hs to avoid poluting the main file with
unrelated auxiliary functions.
I've also used this opportunity to refactor the definition of
help (which I had to modify anyway) so that we don't have
to manually align the commands.
> [ feature ] Looking up a recipe based on its index

- app/herms.hs
This allows listing the recipes sorted by tag, by using the command `herms list --sort tags`.
> Add option to "list" command to sort by tags

- herms.cabal
- src/UnitConversions.hs
In response to issue 28, this introduces `UnitConversions.hs` to `src`. Its `convertRecipeUnits` function takes a unit designation (`0` for metric, `1` for imperial) and a `Recipe`. It then returns a `Recipe` with units converted to the selected system.
> Start to UnitConversions (issue 28)

- .travis.yml
- herms.cabal
Brick no longer supports GHC 7, so we will unfortunately not be able to either :(
> No more legacy support for GHC 7

- Contributing.md
- PULL_REQUEST_TEMPLATE.md
- README.md
- app/herms.hs
It does fix two crashes, though there are no issues for them.
In particular, this fixes:
* a crash when no description is given for some recipe
* a crash when saving when the temporary file is on a different device from the recipe file
* Remove trailing whitespaces (fc90de4) (there is no harm in it and my editor does this automatically through `editorconfig`).
* Make `takeFullWords` total (2034141) (for finite lists, at least)
`takeFullWords` was not total; specifically, it would fail on empty
strings (such as blank descriptions in recipes).
* Fix `replaceDataFile` for different devices (0dfcd99)
`replaceDataFile` would fail with `eXDEV` when moving the temp file to
another device; this is circumvented by instead copying and then
deleting the temp file if the error is thrown.
This was …
> Fix some bugs

- app/herms.hs
- src/Lang/Strings.hs
Fixes #59. It seems to me that recipes are imported with `read`, so exporting them is as easy as `show`. Let me know if I'm mistaken!
Of course, this will have to be changed to be maintained if #45 is implemented.
> Add export functionality

- .travis.yml
This PR restores the usage of two jobs (-j2) in TravisCI after changing it to -j1to enable #82 to avoid failing due to out-of-memory errors.
> Restore using -j2 in TravisCI

- README.md
#84 
Noted in same section as the other supported languages. New section reads:
- Bonjour! Herm's now has language support for, Français (French), English
Pirate, Portuguese, and Español (Spanish). Set your language preferences in ``config.hs``! These are   but the first languages that Herm's is now capable of supporting. We need your help to
translate it into others!
Perhaps you may want to consider including a "Supported Languages" sections that lists all supported langues in a bulleted list.
> Updated supported languages to include Spanish in README

- app/herms.hs
* Switch from show to Yaml.encode to save recipes.
This is a bug fix for issue #90 
Does this pull request address a current issue or idea in Contributing.md?
No.
> Fix recipe saving (#90)

- herms.cabal
- src/UnitConversions.hs
- test/Main.hs
- test/UnitConversions/Tests.hs
Hi,
this is my first pull request and addresses issue #39.
It will only convert temperatures in the form of "110°F" or "90 °C" but not something like "40 degree fahrenheit" (for now).
I haven't worked with Haskell very much and am not familiar with the solution implied here:
>This might be a little more involved as it will require parsing [...]. Luckily, things like this are pretty straightforward in Haskell
I implemented it by matching the text with a regex and am not sure if this is the straigtforward solution.
I am happy about any feedback to this pr.
> Convert oven temperatures in recipe directions between Fahrenheit and Celsius (#39)

- app/herms.hs
The old implementation used [option auto] which relies on Read instance of the returned type.
This doesn't play nicely with String as [Read String] parses quoted strings like `"yaml"`, not `yaml`.
We can either use [option str] or [strOption] but I chose the former just because it looks nicer to me.
> Fixed formatP parser so that it reads plain string.

- src/UnitConversions.hs
Hi @JackMiranda I have started working on #40 and noticed that the conversion for cups & ounces were inverted
> Fix cup & ounce unit conversion

- src/Lang/Portuguese.hs
Pre-patch, `cabal haddock` fails with
```
src/Lang/Portuguese.hs:78:3: error:
parse error on input ‘-- | is datadir        = "datadir"’
|
78 |   -- | is datadir        = "datadir"
|   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The problem is that the commented out code starting with `-- |` happens to be (invalid) Haddock notation. This also causes the nix build to fail as noted in #100 (but this PR doesn't close the issue as it also mentions `stack build` failing when nix integration is enabled).
Post-patch, `cabal haddock` succeeds and so does `nix build -f ./nix`.
> Fix Haddock typo in Portuguese.hs

- herms.cabal
- nix/pinned-pkgs.nix
- nix/shell.nix
- stack.yaml
Fixes #100. I think it also fixes Stack builds in general, since `lts-12.12` provides `yaml-0.8.32` which doesn't satisfy the `yaml >=0.10 && <0.12` constraint `herms.cabal` requires.
It's really only a partial solution though, as peoples' `<nixpkgs>` will always drift from whatever Stack LTS picked (especially since some will be using `nixos` channels and others `nixpkgs-unstable`). Nix-enabled Stack supports being run in a Nix shell, which could use the same pinned nixpkgs as the Nix build does, and so "just work" in the same way by default. If agreed on, I can make a PR for that.
> lts-12.12 -> lts-14.16

- nix/stack.nix
- stack.yaml
Nix-enabled builds will use the pinned nixpkgs by default, which can be overridden by, e.g.,
```
stack build --nix-shell-options='--arg nixpkgs <nixpkgs>'
```
Stack builds without Nix integration will be unaffected.
> Pin nixpkgs by default for Nix-enabled Stack builds

- data/recipes.yaml
- src/Types.hs
Fixes #108 
A good next step/follow-up issue would be to make these fields truly optional by adding a `Maybe` around them, rather than encoding this with a default value, as in this PR.
> recipe: allow some empty fields in YAML/JSON

- herms.cabal
- src/Types.hs
- test/Instances.hs
- test/Types/Tests.hs
Does this pull request address a current issue or idea in Contributing.md?
#110 
Tell us what you did!
* Quantity parser: now accepts number or string. <s>However, due to library limitations, this may introduce some overhead caused by backtracking. Probably minimal</s> Update: no backtracking since the parsers do not overlap.
* Yaml serialization: will now serialize quantities as numbers whenever possible. Simplified `showFrac`.
* Title border box will now contain multi-width characters properly.
* Fix QuickCheck property test for encode -> decode invariance. Added shrinking to ingredient/unit `Arbitrary` instance. Change unit `Arbitrary` instance so that `Other` units do not overlap with synonyms for the rest of the units.
Before:
After:
Do you have any questions? :)
> Yaml parser will now accept num or string as quantity. (+minor cleanup/improvements)

- src/Types.hs
- test/Instances.hs
- test/Types/Tests.hs
Benchmark (99% CI):
* 1M iteration of (readFrac . showFrac) QuickCheck with fixed seed
Old implementation: 32.91s +-0.00
New implementation: 14.21s +-0.00 (67% decrease)
Other changes:
Made it so that the tests only tested positive quantites. Negative
quantities make no sense in this application anyway so we shall not
provide a guarantee on the program's correctness. The old parser parsed
negative improper fractions incorrectly anyway.
Does this pull request address a current issue or idea in Contributing.md?
no
Tell us what you did!
see above
Do you have any questions? :)
no
> Improve readFrac so that the input string is read only once (almost)

- app/herms.hs
- herms.cabal
- stack.yaml
- test/Instances.hs
* Bump base to 4.10 (GHC 8.2)
* Bump resolver to lts-15 (GHC 8.8)
* Remove unnecessary dependency on semigroups, generic-random
* Remove unnecessary dependency on split in the executable
* Bump upper bound for ansi-terminal, brick
* Bump lower bound on bytestring to the one shipped with GHC 8.2
* Introduce bounds on aeson to current in lts-15.1
* Introduce bounds on directory to the one shipped with GHC 8.2
* Introduce upper bound on text-zipper, bump lower bound
* Reformat bounds so that they are consistent
----
Does this pull request address a current issue or idea in Contributing.md?
#107 
Tell us what you did!
Do you have any questions? :)
> Use lts-15 (GHC 8.8) and update bounds.

- .gitignore
- herms.cabal
Relates to #120.
`cabal v2-test` is confirmed to pass.
> Make `nix build` work by relaxing `vty` bound

- .github/workflows/build.yml
For #67, here's a workflow that builds herms when you push a tag to github. Since herms is a heavy build (it clocks in at 10 minutes on github) I limited it to tagged versions; you can remove that limitation by removing the `tags:` part in the workflow.
This also creates a release when it finishes building. I set it to default to a draft release (`draft:`), and it's pulling the entire changelog in as the release message (`body_path:`); you'll want to tweak that, probably.
Finally, I realized that herms could probably benefit from a proper install script, given that it depends on file paths that are hard-coded in by `stack`. Although they are included in the release as assets, it still requires manual download and copying, and knowing where things need to go, and so on.
To kick this off, …
> Add git build action

- src/Html.hs
This PR adds a meta tag to the HTML layout of exported docs in order to specify UTF-8 as the document's charset, as suggested in issue #134. This is done at the beginning of the `<head>` block, right before any other tags.
Closes #134 (if merged).
Let me know if I missed something or if there's anything else I can help with!
> feat: specify utf-8 encoding on exported html

- app/herms.hs
While compiling the project in order to run the tests in #137, GHC spew out this warning:
```bash
path/to/herms/app/herms.hs:274:21: warning: [-Wunused-matches]
Defined but not used: ‘inputTags’
|       
274 | listByTags nameOnly inputTags recipesWithIdx = do
|                     ^^^^^^^^^
```
I checked the code and `listByTags` was only being called by `list` (in the same file), and sure enough the parameter `inputTags` was not being used, so I removed it from `listByTags`'s signature and type annotation, and removed the value being passed as an argument in the call within `list`.
All tests passed (at least in my local environment) and I could run the tool to list the recipes successfully.
As before, let me know if there's anything else I could do to help!
> refactor: remove unused arg on `listByTags`
